/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package gui;

import java.io.File;
import java.util.ArrayList;
import utils.FileUtils;

/**
 *
 * @author drosa
 */
public class TrainingFileDialog extends javax.swing.JDialog {

    ArrayList<String> files = null;
    boolean ok = false;
    String fileChoosed = "";
    
    /**
     * Creates new form TrainingFileDialog
     */
    public TrainingFileDialog(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }

    public void setTrainingFiles (ArrayList<String> files){
        this.files = files;
        cbFiles.removeAllItems();
                
        for (int i=0;i<files.size();i++){
            String fileNamePath = files.get(i);
            File fileData = new File(fileNamePath);
            System.out.println("file: "+fileData.getName());
            cbFiles.addItem(fileData.getName());
        }
    }

    public boolean isOk() {
        return ok;
    }

    public void setOk(boolean ok) {
        this.ok = ok;
    }

    public String getFileChoosed() {
        return fileChoosed;
    }

    public void setFileChoosed(String fileChoosed) {
        this.fileChoosed = fileChoosed;
    }

    public ArrayList<String> getFiles() {
        return files;
    }

    public void setFiles(ArrayList<String> files) {
        this.files = files;
    }
    
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bOk = new javax.swing.JButton();
        bCancel = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        cbFiles = new javax.swing.JComboBox();
        cbEURUSD = new javax.swing.JCheckBox();
        cbGBPUSD = new javax.swing.JCheckBox();
        cbAUDUSD = new javax.swing.JCheckBox();
        cbDayOfWeek = new javax.swing.JCheckBox();
        bFilter = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Select File");

        bOk.setText("Ok");
        bOk.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bOkActionPerformed(evt);
            }
        });

        bCancel.setText("Cancel");
        bCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bCancelActionPerformed(evt);
            }
        });

        jLabel1.setText("Training File");

        cbEURUSD.setSelected(true);
        cbEURUSD.setText("EURUSD");

        cbGBPUSD.setSelected(true);
        cbGBPUSD.setText("GBPUSD");

        cbAUDUSD.setSelected(true);
        cbAUDUSD.setText("AUDUSD");

        cbDayOfWeek.setSelected(true);
        cbDayOfWeek.setText("DayOfWeek");

        bFilter.setText("Filter");
        bFilter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bFilterActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(jLabel1)
                .addGap(33, 33, 33)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(cbGBPUSD)
                        .addGap(17, 376, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(cbEURUSD)
                                .addGap(18, 18, 18)
                                .addComponent(cbDayOfWeek)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(bFilter)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addComponent(cbFiles, 0, 431, Short.MAX_VALUE))
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(cbAUDUSD)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(bOk)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(bCancel)
                        .addGap(17, 17, 17))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(58, 58, 58)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(cbFiles, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cbEURUSD)
                    .addComponent(cbDayOfWeek)
                    .addComponent(bFilter))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 6, Short.MAX_VALUE)
                .addComponent(cbGBPUSD)
                .addGap(3, 3, 3)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cbAUDUSD)
                    .addComponent(bOk)
                    .addComponent(bCancel))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bCancelActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
    }//GEN-LAST:event_bCancelActionPerformed

    private void bOkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bOkActionPerformed
        // TODO add your handling code here:
        ok = true;
        cbFiles.getSelectedIndex();
        for (int i=0;i<files.size();i++){
            if (files.get(i).contains((String)cbFiles.getSelectedItem())){
                fileChoosed = files.get(i);
                this.setVisible(false);
                return;
            }
        }
        
                
    }//GEN-LAST:event_bOkActionPerformed

    private void bFilterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bFilterActionPerformed
        // TODO add your handling code here:
        cbFiles.removeAllItems();
        for (int i=0;i<files.size();i++){
            String fileNamePath = files.get(i);
            File fileData = new File(fileNamePath);
            if (cbEURUSD.isSelected() 
                    && fileData.getName().contains("EURUSD")
                    && !FileUtils.containsDayOfWeek(fileData.getName())){
                System.out.println("file: "+fileData.getName());
                cbFiles.addItem(fileData.getName());
            }   
            if (cbGBPUSD.isSelected() && fileData.getName().contains("GBPUSD")
                   && !FileUtils.containsDayOfWeek(fileData.getName())){
                System.out.println("file: "+fileData.getName());
                cbFiles.addItem(fileData.getName());
            }
            if (cbAUDUSD.isSelected() && fileData.getName().contains("AUDUSD")
                    && !FileUtils.containsDayOfWeek(fileData.getName())){
                System.out.println("file: "+fileData.getName());
                cbFiles.addItem(fileData.getName());
            }
            if (cbDayOfWeek.isSelected() && FileUtils.containsDayOfWeek(fileData.getName())){
                System.out.println("file: "+fileData.getName());
                cbFiles.addItem(fileData.getName());
            }
        }
    }//GEN-LAST:event_bFilterActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TrainingFileDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TrainingFileDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TrainingFileDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TrainingFileDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                TrainingFileDialog dialog = new TrainingFileDialog(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bCancel;
    private javax.swing.JButton bFilter;
    private javax.swing.JButton bOk;
    private javax.swing.JCheckBox cbAUDUSD;
    private javax.swing.JCheckBox cbDayOfWeek;
    private javax.swing.JCheckBox cbEURUSD;
    private javax.swing.JComboBox cbFiles;
    private javax.swing.JCheckBox cbGBPUSD;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
